# Generated by Django 2.2.17 on 2021-01-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='短い説明')),
                ('consciousness', models.TextField(blank=True, null=True, verbose_name='意識していること')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100, verbose_name='コース')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('place', models.CharField(max_length=100, verbose_name='場所')),
                ('period', models.CharField(max_length=100, verbose_name='期間')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='サブタイトル')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('job', models.TextField(verbose_name='仕事')),
                ('introduction', models.TextField(verbose_name='自己紹介')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='github')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='twitter')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='linkedin')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram')),
                ('topimage1', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像')),
                ('topimage2', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像')),
                ('topimage3', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像')),
                ('subimage', models.ImageField(upload_to='images', verbose_name='サブ画像')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サムネイル')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ソフトウェア')),
                ('level', models.CharField(max_length=100, verbose_name='レベル')),
                ('percentage', models.IntegerField(verbose_name='パーセンテージ')),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テクニカル')),
                ('level', models.CharField(max_length=100, verbose_name='レベル')),
                ('percentage', models.IntegerField(verbose_name='パーセンテージ')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サムネイル')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='GithubURL')),
                ('created', models.DateField(verbose_name='作成日')),
                ('worksTitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='作品タイトル')),
                ('numberOfPeople', models.CharField(blank=True, max_length=100, null=True, verbose_name='チーム開発か個人開発か')),
                ('movieUrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='MovieURL')),
                ('worksDescription', models.TextField(blank=True, null=True, verbose_name='その作品についての説明')),
                ('hardshipDescription', models.TextField(blank=True, null=True, verbose_name='苦労した点について')),
                ('learning', models.TextField(blank=True, null=True, verbose_name='そこから学んだこと')),
                ('thoughs', models.TextField(blank=True, null=True, verbose_name='感想')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Skill', verbose_name='スキル')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='技術名')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='その技術を使った最高傑作のURL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='その技術についての説明')),
                ('goodBad', models.TextField(blank=True, null=True, verbose_name='その技術の苦手・得意')),
                ('aim', models.TextField(blank=True, null=True, verbose_name='次の目標')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Skill', verbose_name='スキル')),
            ],
        ),
    ]
